### PR TITLE
Fix double-voicing wrt issue #1265

### PR DESCRIPTION
**Pull request by creffett**

### CODE REVIEW

**Comment by pefoley2** [comment]
Move the lock outside of the for loop, so we don't reacquire it as much.
Maybe add a test too? :)

**Comment by creffett** [comment]
Lock moved. I have a test in my repo, but I can't verify it--the tests are hanging and eating up all my CPU.

**Comment by pefoley2** [comment]
Add it anyway, I'll take a look and see if I can figure out the issue.

**Comment by pefoley2** [comment]
If somebody changes their nick before the initial response from whox comes back, they won't have an entry in .voiced, causing the code to break.

**Comment by creffett** [comment]
Given that they weren't getting an entry at all before, I don't think
that's a regression. That said, I'm open to suggestions on how to handle
it better.

**Comment by pefoley2** [comment]
Don't have it throw an attribute error or w/e.
Just check for that condition when doing .pop()

**Comment by pefoley2** [comment]
I'll take another look once this is rebased. Might as well squash the commits while you're at it.

**Pull request merged**
