### PR TITLE
fixed description for caps hook

### PR DESCRIPTION
**Pull request by laudiacay**
It doesnt warn people so i took that out.

### CODE REVIEW

**Comment by pefoley2** [comment]
You added some extraneous whitespace, other than that it looks good.

**Comment by laudiacay** [comment]
I told you so bobtwinkles :) yay sorry just learning to use git so stupid
requests incoming
Le lun. 26 janv. 2015 à 15:51, Peter Foley <notifications@github.com> a
écrit :

**Comment by pefoley2** [comment]
Git has automagic to squash whitespace, or you can just review the diffs before pushing :)

**Comment by pefoley2** [comment]
Rebased and merged.

**Pull request closed without merging**
