### PR TITLE
Add optional parameter to !mode to specify the target channel, fixes #854

### LINKED ISSUE #854: the bot should be able to !mode for a specific channel
Issue created by lburton!lrburton@hyperion.mrow.org

### PR DESCRIPTION
**Pull request by creffett**

### CODE REVIEW

**Comment by pefoley2** [comment]
I've been moving commands to use argparse instead of custom argument parsing.
Could you change this to use argparse too? commands/grep.py should provide a good example.

**Comment by creffett** [comment]
Done and ready for review.

**Comment by pefoley2** [comment]
Why don't you just add a positional nargs='+' mode param instead of using parse_known_args?

**Comment by pefoley2** [comment]
Merged w/ follow-up fixes/cleanup.

**Pull request closed without merging**
