### PR TITLE
Error propegation for commands and hooks

### PR DESCRIPTION
**Pull request by bobtwinkles**
what it says on the tin

### CODE REVIEW

**Comment by pefoley2** [comment]
I've got a few changes I want to make to this.

**Comment by bobtwinkles** [comment]
@pefoley2, @csssuf, @anyone-else-who-runs-a-bot: This PR requires a real bot restart, not just a !reload because it modifies the logic in `bot.py` significantly, which I still haven't figured out how to reload properly... As such, I'll hold off merging this until I get a ping from at least the 2 of you (either here or on IRC).

**Comment by csssuf** [comment]
As I said in IRC, I'm cool with this.

**Comment by pefoley2** [comment]
I mean, anything that touches bot.py need a restart.

**Pull request merged**
