### PR TITLE
last posted only works within a week now

### LINKED ISSUE #798: forget previously posted urls after a while, since urls may be re-used after a time
Issue created by fwilson!fwilson@wikipedia/Fox-Wilson

### PR DESCRIPTION
**Pull request by laudiacay**
Bot will only now say "last posted" if it was last posted within the last week. issue fix #798

### CODE REVIEW

**Comment by pefoley2** [comment]
I'd do something like:
if last and (time.time() - last.time) < 604800
Also add a comment saying that the magic number is a week in seconds.
Also add "fixes #num" to the patch description rather than replying to the original issue.

**Comment by pefoley2** [comment]
Please use git rebase -i to combine the commits so we have a cleaner git history.

**Comment by laudiacay** [comment]
Wat
Le mer. 28 janv. 2015 à 22:42, Peter Foley <notifications@github.com> a
écrit :

**Comment by pefoley2** [comment]
See http://git-scm.com/book/en/v2/Git-Branching-Rebasing, ask in irc if you're still confused.

**Comment by pefoley2** [comment]
Rebased and merged.

**Pull request closed without merging**
