### PR TITLE
hi yes let's shorten !urban

### PR DESCRIPTION
**Pull request by sckasturi**
hi yes this is a description. it's supposed to say something about shortening !urban to !ud

### CODE REVIEW

**Comment by pefoley2** [comment]
this is getting ridiculous...

**Comment by sckasturi** [comment]
yes but why not shorten commands. it saves keystrokes, plus it isn't
hurting anyone.

**Comment by pefoley2** [comment]
I feel like it won't be used much, and I'm not sure it's worth it.

**Comment by sckasturi** [comment]
it's a click of the button…not that hard

**Comment by pefoley2** [comment]
You're missing the point entirely.
There is a minimum usefulness threshold, and I am not at all convinced that this crosses it.

**Comment by creffett** [comment]
-1, no point.

**Comment by csssuf** [comment]
-1, creffett and pfoley pretty much covered it. I think this is sufficient consensus to close this.

**Pull request closed without merging**
